language: java

jdk:
  - oraclejdk11
  - oraclejdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
  - secure: TNCpO/aNqx4YXjC06LVuv5mseDmg/uWs5TKh54v61tPfVPZfgLZucQjYg1Nt+aZ4O9zVlGG7Bz+6ZztdOc8tHdHVf97qUNEFwEbLKW8y09zsmhSwiDIkLtSV8A7Cl1ZSyMLLIvqeCqbm2ZxDEpteoxMIWc6+idOF0WfVEwb1t5g=
  - secure: LhB92RZqepWvV8sOgbZ54uPO3ZA7zMdktTgqrupyyr3tNNNnJfa+d2h7mPykQKgH1PC1pcrDQZLKGrr+C5+NuEKIcneKq6kHlm80iTQsPMv45QBUFGhJB7L1tXnYnocCLrsJ35PUhv8U3Kx9CB4jjOJ0cMhFUyNNc1VbngfnfWk=
